---
galaxy_info:
  author: Luke Hinds
  description: Ansible Keylime
  company: Red Hat
  license: license (Apache License 2.0)
  min_ansible_version: 2.9
  platforms:
    - name: Fedora
      versions:
        - 31
        - 30
  galaxy_tags: []
dependencies: []
