---
# requirements
dependencies:
  ['PyYAML',
   'autoconf',
   'autoconf-archive',
   'automake',
   'compat-openssl10-devel',
   'dbus-devel',
   'gcc',
   'git',
   'glib2-devel',
   'keylime',
   'libcurl-devel',
   'libgcrypt-devel',
   'libstdc++-devel',
   'libtool',
   'libffi-devel',
   'pkg-config',
   'python3-cryptography',
   'python3-devel',
   'python3-yaml',
   'python3-simplejson',
   'python3-sqlalchemy',
   'redhat-rpm-config',
   'tpm2-tools',
   'tpm2-tss',
   'uriparser-devel']

# section for vars
shell_profiles:
  - .bash_profile

